// Mock data para toda a aplicação
export const mockUser = {
  id_usuario: 1,
  usuario: "João Silva",
  email: "joao@musicconnect.com",
  telefone: "(11) 99999-9999",
  tipo_usuario: "artista",
  local_atuacao: "São Paulo, SP",
  descricao:
    "Guitarrista profissional com 10 anos de experiência. Especializado em rock, blues e jazz.",
  cor_tema: "#ec4899",
  cor_banner: "#18181b",
};

export const mockArtists = [
  {
    id_usuario: 2,
    usuario: "Maria Santos",
    tipo_usuario: "artista",
    local_atuacao: "Rio de Janeiro, RJ",
    descricao: "Cantora e compositora. Repertório variado de MPB e Pop.",
    disponivel: true,
  },
  {
    id_usuario: 3,
    usuario: "Banda Retro",
    tipo_usuario: "banda",
    local_atuacao: "Belo Horizonte, MG",
    descricao: "Banda de rock clássico dos anos 80 e 90.",
    disponivel: true,
  },
  {
    id_usuario: 4,
    usuario: "Pedro Lima",
    tipo_usuario: "artista",
    local_atuacao: "Curitiba, PR",
    descricao: "DJ e produtor musical. Especializado em música eletrônica.",
    disponivel: false,
  },
  {
    id_usuario: 5,
    usuario: "Ana Costa",
    tipo_usuario: "artista",
    local_atuacao: "Salvador, BA",
    descricao: "Violonista clássica. Disponível para eventos corporativos.",
    disponivel: true,
  },
];

export const mockProposals = [
  {
    id_contrato: 1,
    titulo: "Show em Casa de Eventos",
    data: "2026-03-15",
    hora: "21:00",
    valor: "R$ 2.500,00",
    status: "pendente",
    contratante: "Espaço Cultural XYZ",
    descricao: "Show de 2 horas em casa de eventos no centro da cidade.",
  },
  {
    id_contrato: 2,
    titulo: "Apresentação em Festa Particular",
    data: "2026-03-20",
    hora: "19:00",
    valor: "R$ 1.800,00",
    status: "pendente",
    contratante: "Carlos Mendes",
    descricao: "Festa de aniversário com 100 convidados.",
  },
  {
    id_contrato: 3,
    titulo: "Festival de Música",
    data: "2026-04-10",
    hora: "20:00",
    valor: "R$ 5.000,00",
    status: "aceito",
    contratante: "Prefeitura Municipal",
    descricao: "Participação no festival anual da cidade.",
  },
];

export const mockProposalsSent = [
  {
    id_proposta: 1,
    titulo: "Show para Casamento",
    artista: "Maria Santos",
    id_artista: 2,
    data: "2026-03-25",
    hora: "18:00",
    valor: "R$ 3.000,00",
    status: "pendente",
    descricao: "Show para casamento com repertório personalizado.",
    dataEnvio: "2026-02-15",
  },
  {
    id_proposta: 2,
    titulo: "Performance em Eventos Corporativo",
    artista: "Banda Retro",
    id_artista: 3,
    data: "2026-03-28",
    hora: "20:00",
    valor: "R$ 4.500,00",
    status: "aceito",
    descricao: "Performance de 3 horas para evento corporativo.",
    dataEnvio: "2026-02-10",
  },
  {
    id_proposta: 3,
    titulo: "DJ para Festa de Formatura",
    artista: "Pedro Lima",
    id_artista: 4,
    data: "2026-04-05",
    hora: "22:00",
    valor: "R$ 2.200,00",
    status: "recusado",
    descricao: "DJ para festa de formatura com 200 convidados.",
    dataEnvio: "2026-02-08",
  },
  {
    id_proposta: 4,
    titulo: "Apresentação em Evento Corporativo",
    artista: "Ana Costa",
    id_artista: 5,
    data: "2026-04-12",
    hora: "19:00",
    valor: "R$ 2.800,00",
    status: "pendente",
    descricao: "Apresentação musical para coquetel corporativo.",
    dataEnvio: "2026-02-12",
  },
];

export const mockPosts = [
  {
    id: 1,
    title: "Show no Ibirapuera",
    likes: 120,
    comments: 45,
    color: "#7c3aed",
  },
  {
    id: 2,
    title: "Bastidores Gravação",
    likes: 85,
    comments: 12,
    color: "#2563eb",
  },
  {
    id: 3,
    title: "Novo Setup de Luz",
    likes: 230,
    comments: 55,
    color: "#ec4899",
  },
];
